import 'dart:io';

import 'package:path/path.dart' as p;

import '../data/maintenance_audit_ids.dart';
import '../models/audit.dart';
import '../models/audit_run_result.dart';
import '../models/project_context.dart';
import '../models/security_issue.dart';
import '../models/severity.dart';

/// Generates a self-contained HTML security & dependency audit report,
/// complete with a severity-distribution chart. The file has no external
/// dependencies (no CDN scripts/styles) so it renders correctly when opened
/// directly from disk (`file://`).
class HtmlReporter {
  const HtmlReporter();

  static const _severityColors = {
    Severity.critical: '#dc2626',
    Severity.high: '#ea580c',
    Severity.medium: '#d97706',
    Severity.low: '#2563eb',
    Severity.info: '#64748b',
  };
  static const _maintenanceColor = '#7c3aed';
  static const _passedColor = '#16a34a';

  /// Builds the HTML report and writes it to [outputPath], returning the
  /// written [File].
  File writeReport(
    List<AuditRunResult> results, {
    required ProjectContext context,
    String outputPath = 'audit_report.html',
  }) {
    final html = generateHtml(results, context: context);
    final file = File(outputPath);
    file.parent.createSync(recursive: true);
    file.writeAsStringSync(html);
    return file;
  }

  /// Builds the full HTML document as a string.
  String generateHtml(
    List<AuditRunResult> results, {
    required ProjectContext context,
  }) {
    final securityIssues = <SecurityIssue>[];
    final maintenanceIssues = <SecurityIssue>[];
    final passedAudits = <Audit>[];

    for (final run in results) {
      if (!run.result.hasIssues) {
        passedAudits.add(run.audit);
        continue;
      }
      if (maintenanceAuditIds.contains(run.audit.id)) {
        maintenanceIssues.addAll(run.result.issues);
      } else {
        securityIssues.addAll(run.result.issues);
      }
    }

    final bySeverity = {
      for (final severity in Severity.values)
        severity: securityIssues
            .where((issue) => issue.severity == severity)
            .toList(),
    };

    final projectName = p.basename(context.rootPath);
    final now = DateTime.now();
    final date =
        '${now.year.toString().padLeft(4, '0')}-'
        '${now.month.toString().padLeft(2, '0')}-'
        '${now.day.toString().padLeft(2, '0')} '
        '${now.hour.toString().padLeft(2, '0')}:'
        '${now.minute.toString().padLeft(2, '0')}:'
        '${now.second.toString().padLeft(2, '0')}';

    final buffer = StringBuffer()
      ..writeln('<!DOCTYPE html>')
      ..writeln('<html lang="en">')
      ..writeln('<head>')
      ..writeln('<meta charset="UTF-8">')
      ..writeln(
        '<meta name="viewport" content="width=device-width, initial-scale=1.0">',
      )
      ..writeln('<title>Flutter Auditor Report — $projectName</title>')
      ..writeln('<style>${_css()}</style>')
      ..writeln('</head>')
      ..writeln('<body>')
      ..writeln('<div class="page">');

    _writeHeader(
      buffer,
      projectName: projectName,
      context: context,
      date: date,
    );
    _writeSummaryAndChart(
      buffer,
      bySeverity: bySeverity,
      maintenanceCount: maintenanceIssues.length,
      passedCount: passedAudits.length,
    );

    for (final severity in [Severity.critical, Severity.high]) {
      _writeIssueSection(
        buffer,
        title: '${severity.label} Risk',
        color: _severityColors[severity]!,
        issues: bySeverity[severity]!,
      );
    }
    _writeIssueSection(
      buffer,
      title: 'Medium Risk',
      color: _severityColors[Severity.medium]!,
      issues: bySeverity[Severity.medium]!,
    );
    _writeIssueSection(
      buffer,
      title: 'Low Risk',
      color: _severityColors[Severity.low]!,
      issues: [...bySeverity[Severity.low]!, ...bySeverity[Severity.info]!],
      collapsedByDefault: true,
    );
    _writeIssueSection(
      buffer,
      title: 'Maintenance',
      color: _maintenanceColor,
      issues: maintenanceIssues,
      collapsedByDefault: true,
    );
    _writePassedSection(buffer, passedAudits: passedAudits);

    buffer
      ..writeln(
        '<div class="footer">Generated by flutter_auditor on $date</div>',
      )
      ..writeln('</div>')
      ..writeln('</body>')
      ..writeln('</html>');

    return buffer.toString();
  }

  void _writeHeader(
    StringBuffer buffer, {
    required String projectName,
    required ProjectContext context,
    required String date,
  }) {
    final scanned = <String>[
      if (context.androidDirectory.existsSync()) 'android/',
      if (context.iosDirectory.existsSync()) 'ios/',
      if (context.libDirectory.existsSync()) 'lib/',
      if (context.pubspec.existsSync()) 'pubspec.yaml',
    ].join(', ');

    buffer
      ..writeln('<header class="report-header">')
      ..writeln('<h1>Flutter App Security &amp; Dependency Audit</h1>')
      ..writeln('<div class="meta">')
      ..writeln('<span><strong>Project:</strong> ${_esc(projectName)}</span>')
      ..writeln('<span><strong>Scanned:</strong> ${_esc(scanned)}</span>')
      ..writeln('<span><strong>Date:</strong> $date</span>')
      ..writeln('</div>')
      ..writeln('</header>');
  }

  void _writeSummaryAndChart(
    StringBuffer buffer, {
    required Map<Severity, List<SecurityIssue>> bySeverity,
    required int maintenanceCount,
    required int passedCount,
  }) {
    final segments = <_ChartSegment>[
      for (final severity in Severity.values)
        if (bySeverity[severity]!.isNotEmpty)
          _ChartSegment(
            label: severity.label,
            count: bySeverity[severity]!.length,
            color: _severityColors[severity]!,
          ),
      if (maintenanceCount > 0)
        _ChartSegment(
          label: 'Maintenance',
          count: maintenanceCount,
          color: _maintenanceColor,
        ),
    ];

    final total = segments.fold<int>(0, (sum, s) => sum + s.count);
    final highCount =
        bySeverity[Severity.critical]!.length +
        bySeverity[Severity.high]!.length;
    final mediumCount = bySeverity[Severity.medium]!.length;
    final lowCount =
        bySeverity[Severity.low]!.length + bySeverity[Severity.info]!.length;

    final status = highCount > 0
        ? '⚠️ ACTION REQUIRED'
        : mediumCount > 0
        ? '⚠️ REVIEW RECOMMENDED'
        : lowCount > 0
        ? 'ℹ️ MINOR ISSUES'
        : '✅ ALL CLEAR';
    final statusClass = highCount > 0
        ? 'status-bad'
        : (mediumCount > 0 || lowCount > 0)
        ? 'status-warn'
        : 'status-good';

    buffer.writeln('<section class="summary">');

    // Donut chart built from a CSS conic-gradient — no JS/canvas needed.
    buffer.writeln('<div class="chart-card">');
    if (total == 0) {
      buffer.writeln(
        '<div class="donut donut-empty"><div class="donut-hole">'
        '<span class="donut-total">0</span><span class="donut-label">issues</span>'
        '</div></div>',
      );
    } else {
      var cursor = 0.0;
      final stops = <String>[];
      for (final segment in segments) {
        final start = cursor / total * 360;
        cursor += segment.count;
        final end = cursor / total * 360;
        stops.add('${segment.color} ${start}deg ${end}deg');
      }
      buffer.writeln(
        '<div class="donut" style="background: conic-gradient(${stops.join(', ')});">'
        '<div class="donut-hole"><span class="donut-total">$total</span>'
        '<span class="donut-label">issue${total == 1 ? '' : 's'}</span></div>'
        '</div>',
      );
    }

    buffer.writeln('<ul class="legend">');
    for (final segment in segments) {
      buffer.writeln(
        '<li><span class="swatch" style="background:${segment.color}"></span>'
        '${_esc(segment.label)} <strong>${segment.count}</strong></li>',
      );
    }
    if (segments.isEmpty) {
      buffer.writeln('<li>No issues found 🎉</li>');
    }
    buffer.writeln('</ul>');
    buffer.writeln('</div>');

    // Bar chart comparing risk tiers.
    final maxCount = [
      highCount,
      mediumCount,
      lowCount,
      maintenanceCount,
      passedCount,
    ].reduce((a, b) => a > b ? a : b).clamp(1, 1 << 30);
    buffer.writeln('<div class="bar-chart-card">');
    buffer.writeln('<h2>Findings by Category</h2>');
    buffer.writeln('<div class="bars">');
    _writeBar(
      buffer,
      'High',
      highCount,
      maxCount,
      _severityColors[Severity.high]!,
    );
    _writeBar(
      buffer,
      'Medium',
      mediumCount,
      maxCount,
      _severityColors[Severity.medium]!,
    );
    _writeBar(
      buffer,
      'Low',
      lowCount,
      maxCount,
      _severityColors[Severity.low]!,
    );
    _writeBar(
      buffer,
      'Maintenance',
      maintenanceCount,
      maxCount,
      _maintenanceColor,
    );
    _writeBar(buffer, 'Passed', passedCount, maxCount, _passedColor);
    buffer.writeln('</div>');
    buffer.writeln('</div>');

    buffer.writeln('</section>');

    buffer.writeln('<div class="status-banner $statusClass">$status</div>');
  }

  void _writeBar(
    StringBuffer buffer,
    String label,
    int count,
    int maxCount,
    String color,
  ) {
    final pct = (count / maxCount * 100).clamp(0, 100);
    buffer.writeln(
      '<div class="bar-row">'
      '<span class="bar-label">${_esc(label)}</span>'
      '<div class="bar-track"><div class="bar-fill" style="width:$pct%;background:$color"></div></div>'
      '<span class="bar-count">$count</span>'
      '</div>',
    );
  }

  void _writeIssueSection(
    StringBuffer buffer, {
    required String title,
    required String color,
    required List<SecurityIssue> issues,
    bool collapsedByDefault = false,
  }) {
    if (issues.isEmpty) return;

    buffer.writeln(
      '<details class="issue-section" ${collapsedByDefault ? '' : 'open'}>',
    );
    buffer.writeln(
      '<summary style="border-left-color:$color">$title '
      '<span class="count-badge" style="background:$color">${issues.length}</span></summary>',
    );
    buffer.writeln('<div class="issue-list">');
    for (final issue in issues) {
      buffer.writeln(
        '<div class="issue-card" style="border-left-color:$color">',
      );
      buffer.writeln('<h3>${_esc(issue.title)}</h3>');
      buffer.writeln(
        '<div class="issue-location">📍 ${_esc(issue.file)}'
        '${issue.line != null ? ':${issue.line}' : ''}</div>',
      );
      buffer.writeln('<p class="issue-desc">${_esc(issue.description)}</p>');
      buffer.writeln(
        '<p class="issue-fix">✅ <strong>Fix:</strong> ${_esc(issue.recommendation)}</p>',
      );
      buffer.writeln('</div>');
    }
    buffer.writeln('</div>');
    buffer.writeln('</details>');
  }

  void _writePassedSection(
    StringBuffer buffer, {
    required List<Audit> passedAudits,
  }) {
    if (passedAudits.isEmpty) return;

    buffer.writeln('<details class="issue-section">');
    buffer.writeln(
      '<summary style="border-left-color:$_passedColor">Passed '
      '<span class="count-badge" style="background:$_passedColor">${passedAudits.length}</span></summary>',
    );
    buffer.writeln('<ul class="passed-list">');
    for (final audit in passedAudits) {
      buffer.writeln('<li>✔ ${_esc(audit.name)} — no issues found</li>');
    }
    buffer.writeln('</ul>');
    buffer.writeln('</details>');
  }

  String _esc(String input) => input
      .replaceAll('&', '&amp;')
      .replaceAll('<', '&lt;')
      .replaceAll('>', '&gt;')
      .replaceAll('"', '&quot;');

  String _css() => '''
    :root {
      color-scheme: light dark;
      --bg: #0f172a;
      --card-bg: #1e293b;
      --text: #e2e8f0;
      --muted: #94a3b8;
      --border: #334155;
    }
    * { box-sizing: border-box; }
    body {
      margin: 0;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      background: var(--bg);
      color: var(--text);
    }
    .page { max-width: 960px; margin: 0 auto; padding: 32px 20px 64px; }
    .report-header h1 { font-size: 1.6rem; margin-bottom: 8px; }
    .report-header .meta { display: flex; flex-wrap: wrap; gap: 16px; color: var(--muted); font-size: 0.9rem; margin-bottom: 24px; }
    .summary { display: flex; flex-wrap: wrap; gap: 24px; margin-bottom: 16px; }
    .chart-card, .bar-chart-card {
      background: var(--card-bg);
      border: 1px solid var(--border);
      border-radius: 12px;
      padding: 20px;
      flex: 1 1 320px;
      display: flex;
      align-items: center;
      gap: 24px;
    }
    .bar-chart-card { flex-direction: column; align-items: stretch; }
    .bar-chart-card h2 { margin: 0 0 12px; font-size: 1rem; color: var(--muted); }
    .donut {
      width: 140px; height: 140px; border-radius: 50%;
      display: flex; align-items: center; justify-content: center;
      flex-shrink: 0;
    }
    .donut-empty { background: #16a34a; }
    .donut-hole {
      width: 90px; height: 90px; border-radius: 50%;
      background: var(--card-bg);
      display: flex; flex-direction: column; align-items: center; justify-content: center;
    }
    .donut-total { font-size: 1.4rem; font-weight: 700; }
    .donut-label { font-size: 0.75rem; color: var(--muted); }
    .legend { list-style: none; margin: 0; padding: 0; font-size: 0.9rem; }
    .legend li { display: flex; align-items: center; gap: 8px; margin-bottom: 6px; }
    .swatch { width: 12px; height: 12px; border-radius: 3px; display: inline-block; }
    .bars { display: flex; flex-direction: column; gap: 10px; }
    .bar-row { display: grid; grid-template-columns: 90px 1fr 32px; align-items: center; gap: 10px; font-size: 0.85rem; }
    .bar-track { background: #0f172a; border-radius: 6px; overflow: hidden; height: 14px; }
    .bar-fill { height: 100%; border-radius: 6px; }
    .status-banner { text-align: center; padding: 12px; border-radius: 10px; font-weight: 600; margin-bottom: 32px; }
    .status-bad { background: rgba(220,38,38,0.15); color: #f87171; }
    .status-warn { background: rgba(217,119,6,0.15); color: #fbbf24; }
    .status-good { background: rgba(22,163,74,0.15); color: #4ade80; }
    .issue-section { background: var(--card-bg); border: 1px solid var(--border); border-radius: 12px; margin-bottom: 16px; overflow: hidden; }
    .issue-section summary {
      cursor: pointer; padding: 14px 18px; font-weight: 600; font-size: 1rem;
      border-left: 5px solid; list-style: none; display: flex; align-items: center; gap: 10px;
    }
    .issue-section summary::-webkit-details-marker { display: none; }
    .count-badge { color: #0f172a; border-radius: 999px; padding: 1px 9px; font-size: 0.8rem; font-weight: 700; }
    .issue-list { padding: 0 18px 12px; }
    .issue-card { border-left: 3px solid; background: rgba(255,255,255,0.03); border-radius: 8px; padding: 12px 14px; margin: 10px 0; }
    .issue-card h3 { margin: 0 0 6px; font-size: 0.95rem; }
    .issue-location { color: var(--muted); font-size: 0.82rem; margin-bottom: 6px; }
    .issue-desc { margin: 4px 0; font-size: 0.88rem; }
    .issue-fix { margin: 4px 0 0; font-size: 0.88rem; color: #86efac; }
    .passed-list { list-style: none; margin: 0; padding: 4px 18px 16px; color: var(--muted); font-size: 0.88rem; }
    .passed-list li { padding: 3px 0; }
    .footer { text-align: center; color: var(--muted); font-size: 0.8rem; margin-top: 24px; }
  ''';
}

class _ChartSegment {
  final String label;
  final int count;
  final String color;

  const _ChartSegment({
    required this.label,
    required this.count,
    required this.color,
  });
}
