import 'dart:io';

import 'package:path/path.dart' as p;

import '../../data/secret_patterns.dart';
import '../../models/audit.dart';
import '../../models/audit_result.dart';
import '../../models/project_context.dart';
import '../../models/security_issue.dart';

class HardcodedSecretsAudit extends Audit {
  // Generated by `flutterfire configure`. Its apiKey values identify the
  // Firebase project rather than authenticate requests, so Google treats
  // them as safe to ship in client code and they are not real secrets.
  // Flavor setups often rename the file (firebase_options_dev.dart,
  // firebase_options_uat.dart, ...), so match by prefix rather than an
  // exact name.
  static final _ignoredFileNamePattern = RegExp(
    r'^firebase_options.*\.dart$',
    caseSensitive: false,
  );

  static const _placeholderMarkers = [
    'your_',
    'yourkey',
    'xxxx',
    'example',
    'placeholder',
    'changeme',
    'dummy',
    'insert_',
    'replace_',
    'todo',
    'test_key',
    '<',
  ];

  @override
  String get id => 'hardcoded_secrets';

  @override
  String get name => 'Hardcoded Secrets Detection';

  @override
  String get description =>
      'Scans Dart source files for hardcoded API keys, tokens, passwords, and other secrets.';

  @override
  Future<AuditResult> run(ProjectContext context) async {
    final issues = <SecurityIssue>[];

    if (!context.libDirectory.existsSync()) {
      return AuditResult(issues: issues);
    }

    final dartFiles = context.libDirectory
        .listSync(recursive: true)
        .whereType<File>()
        .where((file) => file.path.endsWith('.dart'))
        .where(
          (file) => !_ignoredFileNamePattern.hasMatch(p.basename(file.path)),
        );

    for (final file in dartFiles) {
      final lines = await file.readAsLines();

      for (var lineNumber = 0; lineNumber < lines.length; lineNumber++) {
        _scanLine(
          file: file,
          line: lines[lineNumber],
          lineNumber: lineNumber + 1,
          issues: issues,
        );
      }
    }

    return AuditResult(issues: issues);
  }

  void _scanLine({
    required File file,
    required String line,
    required int lineNumber,
    required List<SecurityIssue> issues,
  }) {
    if (_isLikelyPlaceholder(line)) {
      return;
    }

    var matchedSpecificPattern = false;

    for (final secretPattern in secretPatterns) {
      if (secretPattern.isGeneric && matchedSpecificPattern) {
        continue;
      }

      if (!secretPattern.pattern.hasMatch(line)) {
        continue;
      }

      issues.add(
        SecurityIssue(
          id: '${id}_${file.path}_${lineNumber}_${secretPattern.name}',
          title: 'Hardcoded ${secretPattern.name}',
          description:
              'A potential ${secretPattern.name} was found hardcoded in source code.',
          severity: secretPattern.severity,
          file: file.path,
          line: lineNumber,
          recommendation: secretPattern.recommendation,
        ),
      );

      if (!secretPattern.isGeneric) {
        matchedSpecificPattern = true;
      }
    }
  }

  bool _isLikelyPlaceholder(String line) {
    final lower = line.toLowerCase();

    return _placeholderMarkers.any(lower.contains);
  }
}
